type ChannelFromMain
    = 'yf:initialization'
    | 'yf:tweet'
    | 'yf:mentions'
    | 'yf:user-timeline'
    | 'yf:retweet-success'
    | 'yf:unretweet-success'
    | 'yf:like-success'
    | 'yf:unlike-success'
    | 'yf:update-status-success'
    | 'yf:my-account'
    | 'yf:my-account-update'
    | 'yf:delete-status'
    | 'yf:liked-status'
    | 'yf:follow'
    | 'yf:unfollow'
    | 'yf:connection-failure'
    | 'yf:rejected-ids'
    | 'yf:unrejected-ids'
    | 'yf:no-retweet-ids'
    | 'yf:friends'
    | 'yf:auth-tokens'
    | 'yf:api-failure'
;

type ChannelFromRenderer
    = 'yf:request-retweet'
    | 'yf:undo-retweet'
    | 'yf:request-like'
    | 'yf:destroy-like'
    | 'yf:update-status'
    | 'yf:destroy-status'
    | 'yf:request-follow'
    | 'yf:request-unfollow'
    | 'yf:request-user-timeline'
    | 'yf:start-user-stream'
;
